# Generated by Django 3.0.8 on 2020-07-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20200729_1749'),
        ('users', '0006_remove_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Roles'),
        ),
    ]
