# Generated by Django 3.0.8 on 2020-08-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snortdetails',
            name='sig_id',
        ),
        migrations.AddField(
            model_name='snortdetails',
            name='sig',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='rules.Rules'),
        ),
    ]
