# Generated by Django 3.0.8 on 2020-08-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalManagerGraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('chart_id', models.IntegerField()),
                ('query_data', models.TextField()),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'internal_manager_graphs',
                'managed': True,
            },
        ),
    ]
