# Generated by Django 3.0.8 on 2020-08-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_graphtype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='graphtype',
            table='graph_type',
        ),
    ]
