# Generated by Django 3.0.8 on 2020-08-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20200803_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalmanagergraphs',
            old_name='chart_id',
            new_name='chart',
        ),
    ]
