# Generated by Django 3.0.8 on 2020-07-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermissions',
            unique_together={('role', 'permission')},
        ),
    ]
