# Generated by Django 3.0.8 on 2020-08-04 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'rule_src',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tools',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('rev', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attack_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stix.AttackPatternType')),
                ('course_of_action', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='stix.CourseOfAction')),
                ('malware_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stix.MalwareLabel')),
                ('rule_src', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rules.RuleSource')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rules.Tools')),
            ],
            options={
                'db_table': 'rules',
                'managed': True,
                'unique_together': {('sid', 'rev')},
            },
        ),
    ]
