# Generated by Django 3.0.8 on 2020-08-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='attack_pattern',
            new_name='attack_pattern_type',
        ),
    ]
