# Generated by Django 3.0.8 on 2020-08-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stix', '0001_initial'),
        ('rules', '0002_auto_20200804_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='attack_pattern_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stix.AttackPatternType'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='malware_label',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stix.MalwareLabel'),
        ),
    ]
