"""
Django settings for honeypot_dashboard project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n2#-1!7)qd-dxq6=0x&4cv8y4bt^uj#_!oghr)9bs=4ir_nlmn'

# SECURITY WARNING: don't run with debug turned on in production!
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

ALLOWED_HOSTS = ["*"]
DEBUG = True if env('debug') == "1" else False
# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users',
    'dashboard',
    'roles',

    'compressor',
    'crispy_forms',
    'admin',
    'graphs',
    'rules',
    'stix'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.adminMiddleware.AdminMiddleware',
    'middleware.loginMiddleware.Login'
]

ROOT_URLCONF = 'honeypot_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'honeypot_dashboard.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('mysql_database'),
        'USER': env('mysql_username'),
        'PASSWORD': env('mysql_password'),
        'HOST': env('mysql_host'),
        'PORT': '3306',
        'CONN_MAX_AGE': 3600,
    },
    'subexsecure_auth': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "subexsecure_auth",
        'USER': env('mysql_username'),
        'PASSWORD': env('mysql_password'),
        'HOST': env('mysql_host'),
        'PORT': '3306',
        'CONN_MAX_AGE': 3600,
    }
}
DATABASE_ROUTERS = ['honeypot_dashboard.database_router.AuthRouter.AuthRouter',
                    'honeypot_dashboard.database_router.PrimaryRouter.PrimaryReplicaRouter']
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.Users'
AUTHENTICATION_BACKENDS = ('users.backends.CustomUserAuth',)
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, "assets")
STATICFILES_FINDERS = [
    "compressor.finders.CompressorFinder",
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/user/login'
ADMIN_LOGIN_URL = '/admin/login'
LOGIN_EXEMPT_URLS = (
    r'^admin+',
    'user/setup'
)
CRISPY_TEMPLATE_PACK = 'bootstrap4'
COMPRESS_ENABLED = False if DEBUG else True
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.rCSSMinFilter']
TIME_ZONE = 'Asia/Kolkata'

USE_TZ = False
